### PR TITLE
Name : Anurag Chakraborty LinkedIn : https://www.linkedin.com/in/anurag-chakraborty-841827174/ "edited the align.html file in easy category "

### PR DESCRIPTION
**Pull request by achak47**

### CODE REVIEW

**Comment by ChiragGupta2808** [comment]
Great, @achak47 you have contributed in the repo correctly but you need to give description according to the given format in the README.md file. For now you are on hold, as soon as you will do the required changes we'll merge your PR for the hacktoberfest.

**Comment by achak47** [comment]
I have changed the title of the PR

**Comment by ChiragGupta2808** [comment]
Your one PR has been accepted in Web. Now you can contribute in other domains of GDSC.

**Comment by achak47** [comment]
> Your one PR has been accepted in Web. Now you can contribute in other domains of GDSC.
ok sir

**Pull request closed without merging**
