### PR TITLE
Name : Anurag Chakraborty LinkedIn : https://www.linkedin.com/in/anurag-chakraborty-841827174/ "Added the youtube link embedder , edited 1 file "

### PR DESCRIPTION
**Pull request by achak47**
I have made the html page where a link is inputed by the user and from that the id of the video is extracted and used with iframe to view it

### CODE REVIEW

**Comment by ChiragGupta2808** [comment]
Great, @achak47  you have contributed in the repo correctly but you need to give description according to the given format in the README.md file. For now you are on hold, as soon as you will do the required changes we'll merge your PR for the hacktoberfest.

**Comment by achak47** [comment]
@ChiragGupta2808 , by mistakenly this pull request got closed , I am generating a new pull request with the format given in readme file

**Comment by achak47** [comment]
> Great, @achak47 you have contributed in the repo correctly but you need to give description according to the given format in the README.md file. For now you are on hold, as soon as you will do the required changes we'll merge your PR for the hacktoberfest.

Where do I  add the description , in the PR title or the description , or shall I create a new PR with proper description . Pls kindly guide me for this , I am a bit new to these things

**Comment by achak47** [comment]
I have changed the title of this PR , now is it okay ?

**Pull request merged**
